apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: api-crt-prod
spec:
  secretName: api-crt-prod
  dnsNames:
  - api.triangl.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - api.triangl.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
