apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tracking-ingestion-service
spec:
  template:
    metadata:
      labels:
        app: tracking-ingestion-service
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: google-cloud-key
      containers:
      - name: tracking-ingestion-service
        image: eu.gcr.io/triangl-215714/tracking-ingestion-service:latest
        resources:
          limits:
            cpu: "0.1"
          requests:
            cpu: "0.05"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PUBSUB_TOPICID
          value: ingestion-prod
        - name: SENTRY_DSN
          value: https://e95b3a253e8040f9a32af069e5c6cdc8@sentry.io/1318093
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 2