apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tracking-ingestion-service
spec:
  template:
    metadata:
      labels:
        app: tracking-ingestion-service
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: datastore-key
      containers:
      - name: tracking-ingestion-service
        image: eu.gcr.io/triangl-215714/tracking-ingestion-service:${VERSION}
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
